title: SISK
email: pawel.ksieniewicz@pwr.edu.pl
description: > # this means to ignore newlines until "baseurl:"
  Koło Naukowe Systemów Informatycznych i Sieci Komputerowych</em> dziala przy Katedrze Systemów i Sieci Komputerowych na wydziale Elektroniki Politechniki Wrocławskiej.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sisk.kssk.pwr.edu.pl" # the base hostname & protocol for your site
github_username:  kn-sisk
facebook_username: knsisk
future: true

markdown: kramdown
exclude:
  - Gruntfile.coffee
  - Gemfile
  - Gemfile.lock
  - bower.json
  - package.json
  - bower_components
  - node_modules

gems:
  - jekyll-seo-tag
